<a href="https://colab.research.google.com/github/harshtiwariexe/machine-learning-case-studies/blob/main/Case_2_Diabetes_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This project uses Machine Learning to predict whether a person is diabetic based on medical parameters such as glucose level, blood pressure, BMI, age, and other health indicators. The model is trained on historical patient data and can provide quick predictions to assist in early diabetes risk assessment.

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
diabetes_dataset = pd.read_csv('/content/diabetes.csv')

In [3]:
print(diabetes_dataset)

     Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [4]:
diabetes_dataset.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [6]:
diabetes_dataset.shape

(768, 9)

In [7]:
diabetes_dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [8]:
diabetes_dataset.groupby('Outcome').mean()

         Pregnancies     Glucose  ...  DiabetesPedigreeFunction        Age
Outcome                           ...
0           3.298000  109.980000  ...                  0.429734  31.190000
1           4.865672  141.257463  ...                  0.550500  37.067164

[2 rows x 8 columns]

In [9]:
X = diabetes_dataset.drop(columns='Outcome',axis=1)
Y = diabetes_dataset['Outcome']

In [11]:
print(X)
print(Y)

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [12]:
scaler = StandardScaler()

In [13]:
scaler.fit(X)

StandardScaler()

In [14]:
standard_data = scaler.transform(X)

In [15]:
print(standard_data.std())

1.0

In [16]:
X = standard_data

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [18]:
print(X.shape, X_train.shape, X_test.shape)

(768, 8) (614, 8) (154, 8)

In [19]:
classifier = svm.SVC(kernel='linear')

In [20]:
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

In [22]:
X_train_pred = classifier.predict(X_train)
train_data_accuracy = accuracy_score(X_train_pred,Y_train)

In [23]:
print(train_data_accuracy*100)

78.66449511400651

In [24]:
X_test_pred = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_pred,Y_test)

In [25]:
print(test_data_accuracy*100)

77.27272727272727

In [27]:
sample_data = (0,137,40,35,168,43.1,2.288,33)

input_data = np.asarray(sample_data, dtype=np.float32).reshape(1, -1)

scaled_data = scaler.transform(input_data)

prediction = classifier.predict(scaled_data)

result = "Diabetic" if prediction[0] == 1 else "Non-Diabetic"
print(f"Prediction: {result}")

Prediction: Diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(